forge 'https://forgeapi.puppetlabs.com'

mod 'golja-gnupg', '1.2.3'
mod 'igorolivei-hashicorp_install', '1.0.2'
mod 'lwf-remote_file', '1.1.3'
mod 'puppet/archive', '6.0.2'
mod 'puppet-nodejs', '9.0.1'
mod 'puppet-python', '6.2.1'
mod 'puppetlabs-apt', '3.0.0'
mod 'puppetlabs/stdlib', '8.1.0'
mod 'stahnma-epel', '1.2.2'
mod 'zloesabo-hugo', '0.1.0'
