forge 'https://forgeapi.puppetlabs.com'

mod 'golja-gnupg', '1.2.3'
mod 'igorolivei-hashicorp_install', :git => 'https://github.com/cliffano/puppet-hashicorp_install'
mod 'lwf-remote_file', '1.1.3'
mod 'puppet/archive', '5.0.0'
mod 'puppet-nodejs', '8.1.0'
mod 'puppet-python', '6.0.0'
mod 'puppetlabs/stdlib', '4.21.0'
mod 'stahnma-epel', '1.2.2'
mod 'zloesabo-hugo', '0.1.0'
