---
- hosts: localhost

  vars:
    go_ver: 1.25.0
    hashi_apps:
      - name: packer
        ver: 1.14.2
      - name: terraform
        ver: 1.13.4
    # Available versions: https://github.com/andrewrothstein/ansible-hugo/blob/main/defaults/main.yml
    hugo_ver: 0.146.6

  roles:
    - andrewrothstein.go
    - andrewrothstein.hashi
    - andrewrothstein.hugo

  tasks:

    - ansible.builtin.command: go install github.com/checkmake/checkmake/cmd/checkmake@latest
    - ansible.builtin.command: go install github.com/tomwright/dasel/v2/cmd/dasel@master
