---
- hosts: localhost

  vars:
    hashi_apps:
      - name: packer
        ver: 1.11.2
      - name: terraform
        ver: 1.9.5
    # Available versions: https://github.com/andrewrothstein/ansible-hugo/blob/main/defaults/main.yml
    hugo_ver: 0.134.2

  roles:
    - andrewrothstein.hashi
    - andrewrothstein.hugo

  tasks:

    - ansible.builtin.command: go install github.com/mrtazz/checkmake/cmd/checkmake@latest