---
- hosts: localhost

  vars:
    # Available versions: https://github.com/andrewrothstein/ansible-node/blob/main/defaults/main.yml
    node_ver: 22.7.0

  roles:
    - andrewrothstein.node

  tasks:

    - community.general.npm:
        name: "{{ item.name }}"
        version: "{{ item.version }}"
        global: true
      loop:
        - { "name": "bob", "version": "2.7.0" }
        - { "name": "jazz-cli", "version": "1.0.0" }