---
name: Publish Docker Kon-Tiki Private
'on':
  push:
    tags:
      - '*'
jobs:
  build:
    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04
            arch: amd64
          - runner: ubuntu-24.04-arm
            arch: arm64
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v7
        with:
          ref: main
      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: kontiki818
          password: ${{ secrets.KONTIKI818_GITHUB_TOKEN_CLASSIC }}
      - uses: cliffano/command-docker-action@v2.1.0
        with:
          image: cliffano/studio:4.0.0
          shell: bash
          extra_args: '-v ~/.docker/config.json:/root/.docker/config.json:ro'
          command: >
            make deps clean stage lint build-docker-kon-tiki-private arch=${{ matrix.arch }} &&

            cat logs/packer-docker-kon-tiki-private.log &&

            docker --version &&

            docker info  &&

            docker inspect ghcr.io/cliffano/kon-tiki &&

            make publish-docker-kon-tiki-private arch=${{ matrix.arch }}
  manifest:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: kontiki818
          password: ${{ secrets.KONTIKI818_GITHUB_TOKEN_CLASSIC }}
      - run: make publish-docker-kon-tiki-private-manifest
