---
name: Publish Docker Kon-Tiki
'on':
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
        with:
          ref: main
      - uses: docker/login-action@v4
        with:
          username: cliffano
          password: ${{ secrets.KONTIKI_DOCKERHUB_TOKEN }}
      - uses: cliffano/command-docker-action@v2.1.0
        with:
          image: cliffano/studio:3.2.0
          shell: bash
          extra_args: '-v ~/.docker/config.json:/root/.docker/config.json:ro'
          command: >
            make deps clean stage lint build-docker-kon-tiki &&

            cat logs/packer-docker-kon-tiki.log &&

            docker --version &&

            docker info  &&

            docker inspect cliffano/kon-tiki &&

            make publish-docker-kon-tiki